### ISSUE TITLE
Sync with sunrise and sunset

### ISSUE THREAD

**Issue by 42willow** [Ju1-js/25th-hour-dynamic#1]
It would be great if there was an option to sync the animation with the local sunrise and sunset.

**Comment by Ju1-js** [comment]
I will attempt this, although it’s currently a 12 hour day/night so I’ll have to mess around with some things.

**Comment by Ju1-js** [comment]
There doesn't doesn't seem to be a good way to speed up/slow down sections of a CSS animation dynamically, you could always use the offset to make it closer.

Reopen the issue if you have any feasible suggestions.
