### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by 42willow** [Ju1-js/25th-hour-dynamic#2]
Is it possible to use even less CPU during times when there's no animation playing (trees disabled and nothing moving)? This might just be a limitation with CefSharp though.

**Comment by Ju1-js** [comment]
I’m pretty sure most of the performance hit comes from the gradients, but I will check later.

**Comment by Ju1-js** [comment]
So, most of the performance hit comes from the Landscape... Not much I can really do about that...
Just make sure that the wallpaper pauses when it's not focused or something is fullscreen.
