### ISSUE TITLE
livelyAudioListener not defined in lively console

### ISSUE THREAD

**Issue by 42willow** [Ju1-js/25th-hour-dynamic#5]
![image](https://github.com/Ju1-js/25th-hour-dynamic/assets/70784752/82b8f3b3-d3cb-44b8-95f1-f821b9a63497)

**Comment by Ju1-js** [comment]
To use lively audio listener, it has to be run though lively.

**Comment by 42willow** [comment]
Oops mb

Just realised it's because I'd put in the flag but not the listener.
