### ISSUE TITLE
Where's the pixel noise?

### ISSUE THREAD

**Issue by 42willow** [Ju1-js/25th-hour-dynamic#8]
I can't see it :/

**Comment by Ju1-js** [comment]
Yea, it's barely visible when enabled. However it's disabled by default.
https://www.diffchecker.com/image-compare/
No noise:
![25th-hour-dynamic](https://github.com/Ju1-js/25th-hour-dynamic/assets/40339350/a7c17819-4ff0-4628-81e2-1be54bf4e55f)
Noise:
![25th-hour-dynamic-noise](https://github.com/Ju1-js/25th-hour-dynamic/assets/40339350/bb25e408-06a9-4b6a-88bb-0821b1c45b57)

**Comment by 42willow** [comment]
![image](https://github.com/Ju1-js/25th-hour-dynamic/assets/70784752/4823df52-c416-47c4-97e4-53985f6204fb)
very subtle
