### ISSUE TITLE
Performance stats

### ISSUE THREAD

**Issue by 42willow** [Ju1-js/25th-hour-dynamic#9]
- [x] INCLUDE LICENSES
- [x] Toggle switch
- [x] Option to change animation speed
- [x] Option to change position _(bottom left and bottom right corner, top left and top right is reserved for weather/date/time)_
- [x] Disable rendering when hidden _(for settings and desktop!)_
- [x] Make PR #26

I'll work on this.

**Comment by Ju1-js** [comment]
The main reason, that I've left the settings panel in the code is for the `<div class="counter"></div>` to show what state the animation is in. Also all of the settings panel customization options are at the bottom so as to not be in the way...

**Comment by 42willow** [comment]
What about performance stats in the empty space of the settings panel? I've already got some code from the demo repo.
![image](https://github.com/Ju1-js/25th-hour-dynamic/assets/70784752/86a43f53-1356-4467-ba80-744188eca284)
(yes, my laptop is a potato...)

I can move this to the settings panel and try to disable the rendering when the panel is hidden for performance.

**Comment by Ju1-js** [comment]
If they're going to be hidden behind that panel, I'd just use task manager to see performance. (They also fit the theme quite well)
 
I'd just:
- Make it toggle-able
- Disable rendering when hidden

_P.S. Don't forget the licences if there are any!_

**Comment by 42willow** [comment]
So you think that they should just be on the main desktop or under the side panel?

Yep, I'll remember those licences.

**Comment by Ju1-js** [comment]
Yea, just on the main desktop, otherwise they're kinda pointless.

**Comment by 42willow** [comment]
Ok

**Comment by Ju1-js** [comment]
Merged!
